const $=id=>document.getElementById(id);
async function api(path,opt={}){const r=await fetch(path,opt),j=await r.json();if(!r.ok)throw Error(j.error||"Erro");return j}
function render(s){$("channel").textContent=s.channel||"Nenhuma";$("status").textContent=s.status==="playing"?"🟢 A ver live":"⏹️ Visualização parada";$("online").textContent="● Online";$("online").className="pill ok";const f=$("favorites");f.innerHTML="";(s.favorites||[]).forEach(ch=>{const d=document.createElement("div");d.className="fav";const b=document.createElement("button");b.textContent=ch;b.onclick=()=>selectChannel(ch);const x=document.createElement("button");x.textContent="×";x.className="x";x.onclick=()=>favorite(ch,"remove");d.append(b,x);f.append(d)})}
async function refresh(){try{render(await api("/api/status"))}catch(e){$("online").textContent="● Offline";$("online").className="pill";$("status").textContent="Sem ligação à Raspberry"}}
async function selectChannel(channel){$("controlMessage").textContent="A selecionar "+channel+"…";try{render(await api("/api/channel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel})}));$("controlMessage").textContent="Canal selecionado. Carrega em «Começar a ver»."}catch(e){$("controlMessage").textContent=e.message}}
async function startWatching(){$("controlMessage").textContent="A iniciar a visualização…";try{render(await api("/api/start"));$("controlMessage").textContent="Live iniciada."}catch(e){$("controlMessage").textContent=e.message}}
async function stopWatching(){$("controlMessage").textContent="A terminar a visualização…";try{render(await api("/api/stop"));$("controlMessage").textContent="Visualização terminada."}catch(e){$("controlMessage").textContent=e.message}}
async function favorite(channel,action){try{render(await api("/api/favorite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel,action})}))}catch(e){$("message").textContent=e.message}}
$("openBtn").onclick=()=>{const c=$("channelInput").value.trim();if(c)selectChannel(c)};$("channelInput").addEventListener("keydown",e=>{if(e.key==="Enter")$("openBtn").click()});$("startBtn").onclick=startWatching;$("stopBtn").onclick=stopWatching;$("reloadBtn").onclick=startWatching;$("refreshBtn").onclick=refresh;$("loginBtn").onclick=async()=>{try{$("loginMsg").textContent=(await api("/api/login")).message}catch(e){$("loginMsg").textContent=e.message}};refresh();setInterval(refresh,10000);
